SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing
syncfusion-content/angularjs-docs pull request #280
Opened 2024-08-28 13:11 UTC by Faith-Atieno

Title | Description
-- | --
|Task Category | Coverage Issues|
|Content Task Link/Mail Screenshot | NA|
|Hotfix |https://github.com/syncfusion-content/ej2-javascript-docs/pull/348|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187689|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B2A368E74-D539-456F-9819-C9B68637E490%7D&file=Faith.xlsx&action=default&mobileredirect=true|

Changes Made | Reason for change |
|-- | -- |
|Changed-Redirect link | To avoid redirect links |

2024-08-28 13:12 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/15/console)**

2024-08-28 13:57 UTC, SyncfusionBuild commented
The CI [Job](https://ci.syncfusion.com/job/Content/job/angularjs-docs/15/console) is already running for this Pull Request/Merge Approved with latest commit id. You cannot trigger the duplicate job for same.

2024-08-28 13:58 UTC, Faith-Atieno commented
rebuild

2024-08-28 14:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/15/console)**

2024-08-28 14:28 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/angularjs-docs/15/artifact/cireports/)<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/15/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/15/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/15/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/15/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/15/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](https://ci.syncfusion.com/job/Content/job/angularjs-docs/15/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/15/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/15/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/15/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-29 05:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/16/console)**

2024-08-29 05:42 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/angularjs-docs/16/artifact/cireports/)<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/16/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/16/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/16/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/16/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/16/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/angularjs-docs/16/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/16/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/16/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/16/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-29 05:44 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/17/console)**

2024-08-29 05:45 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/17/console)**

2024-08-29 05:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/17/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/17/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/17/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/17/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/17/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/17/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/17/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/17/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/17/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-29 08:03 UTC, Yvone-Atieno requested changes
Commented

2024-08-29 08:03 UTC, Yvone-Atieno commented on angularjs/Dialog/appearance-and-styling.md
> +# Appearance and styling
Include platform and control name

2024-08-29 08:03 UTC, Yvone-Atieno commented on angularjs/Dialog/appearance-and-styling.md
>  ### Showing header
Change this as H2

2024-08-29 08:27 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/18/console)**

2024-08-29 08:28 UTC, Faith-Atieno commented on angularjs/Dialog/appearance-and-styling.md
>  ### Showing header
resolved

2024-08-29 08:29 UTC, Faith-Atieno commented on angularjs/Dialog/appearance-and-styling.md
> +# Appearance and styling
resolved

2024-08-29 08:29 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/18/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/18/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/18/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/18/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/18/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/18/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/18/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/18/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/18/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-29 13:49 UTC, Yvone-Atieno requested changes
Commented

2024-08-29 13:49 UTC, Yvone-Atieno commented on angularjs/Dialog/appearance-and-styling.md
> +# Appearance and styling in angularjs Dialog
Check the platform name

2024-09-03 07:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/19/console)**

2024-09-03 07:24 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/angularjs-docs/19/artifact/cireports/)<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/19/)<br/>Technical Error(s): [1](https://ci.syncfusion.com/job/Content/job/angularjs-docs/19/artifact/cireports/spellcheck/spellcheckreport.htm)<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/19/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/19/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/19/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/19/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/19/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/19/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/19/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/19/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-03 07:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/20/console)**

2024-09-03 07:37 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/20/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/20/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/20/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/20/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/20/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/20/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/20/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/20/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/20/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-03 13:16 UTC, Yvone-Atieno requested changes
Commented

2024-09-03 13:16 UTC, Yvone-Atieno commented on angularjs/Dialog/appearance-and-styling.md
> +description: Learn here about appearance and styling with Syncfusion Essential Angular Dialog control, its elements, and more.
use in not with

2024-09-10 14:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/21/console)**

2024-09-10 14:01 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/21/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/21/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/21/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/21/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/21/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/21/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/21/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/21/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/21/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-11 08:08 UTC, Yvone-Atieno requested changes
Commented

2024-09-11 08:08 UTC, Yvone-Atieno commented on angularjs/Dialog/appearance-and-styling.md
> +description: Learn here about appearance and styling use in Syncfusion Essential Angular Dialog control, its elements, and more.
Check description and title

2024-09-11 09:09 UTC, Faith-Atieno commented on angularjs/Dialog/appearance-and-styling.md
> +description: Learn here about appearance and styling use in Syncfusion Essential Angular Dialog control, its elements, and more.
resolved

2024-09-11 09:42 UTC, Yvone-Atieno requested changes
Commented

2024-09-11 09:42 UTC, Yvone-Atieno commented on angularjs/Dialog/appearance-and-styling.md
> +description: Learn here about appearance and styling support Syncfusion Angular Dialog control, its elements, and more.
Check title and description

2024-09-11 09:42 UTC, Yvone-Atieno commented on angularjs/Dialog/appearance-and-styling.md
> +# Appearance and styling in Syncfusion Angular Dialog
Remove the word syncfusion

2024-09-11 09:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/23/console)**

2024-09-11 09:49 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/23/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/23/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/23/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/23/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/23/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/23/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/23/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/23/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/23/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-11 11:14 UTC, Faith-Atieno commented on angularjs/Dialog/appearance-and-styling.md
> +# Appearance and styling in Syncfusion Angular Dialog
resolved

2024-09-11 11:17 UTC, Faith-Atieno commented on angularjs/Dialog/appearance-and-styling.md
> +description: Learn here about appearance and styling use in Syncfusion Essential Angular Dialog control, its elements, and more.
resolved

2024-09-11 12:56 UTC, Faith-Atieno commented on angularjs/Dialog/appearance-and-styling.md
> +description: Learn here about appearance and styling support Syncfusion Angular Dialog control, its elements, and more.
resolved

2024-09-16 09:55 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/25/console)**

2024-09-16 09:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/25/console)**

2024-09-16 09:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/25/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/25/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/25/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/25/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/25/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/25/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/25/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/25/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/25/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-17 08:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/26/console)**

2024-09-17 08:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/26/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/26/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/26/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/26/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/26/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/26/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/26/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/26/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/26/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-17 13:32 UTC, Faith-Atieno commented on angularjs/Dialog/appearance-and-styling.md
> +description: Learn here all about Style and appearance in Syncfusion Angular Dialog control, its elements, and more.
resolved

2024-09-18 07:19 UTC, Yvone-Atieno approved these changes
Approved

2024-09-18 13:59 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/27/console)**

2024-09-18 14:01 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/27/console)**

2024-09-18 14:12 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-188026-AngularJS-Dialog-appearance-and-styling-H1-Missing](https://ci.syncfusion.com/job/Content/job/angularjs-docs/27/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/27/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/27/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/27/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/27/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/27/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/27/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/27/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/angularjs-docs/27/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-26 12:23 UTC, Aishwarya-Ganesan approved these changes
fine.

2024-09-26 12:23 UTC, merged